name: Publish to PyPI

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build
        run: python -m build
      - name: Publish
        if: secrets.PYPI_API_TOKEN != ''
        env:
          TWINE_USERNAME: zbirenbaum
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

