name: Tag On Merge

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect version bump
        id: detect
        run: |
          BEFORE=$(git rev-parse HEAD^)
          AFTER=$(git rev-parse HEAD)
          if git diff --name-only "$BEFORE" "$AFTER" | grep -q '^pyproject.toml$'; then
            echo "changed_pyproject=true" >> $GITHUB_OUTPUT
          else
            echo "changed_pyproject=false" >> $GITHUB_OUTPUT
          fi
      - name: Read version
        if: steps.detect.outputs.changed_pyproject == 'true'
        id: readver
        run: |
          python - <<'PY'
          import re
          txt = open('pyproject.toml','r',encoding='utf-8').read()
          m = re.search(r"^version\s*=\s*['\"]([^'\"]+)['\"]", txt, re.M)
          if not m:
            raise SystemExit('version not found')
          print(f"version={m.group(1)}")
          PY
      - name: Tag if missing
        if: steps.detect.outputs.changed_pyproject == 'true'
        run: |
          VERSION=$(python - <<'PY'
          import re
          txt = open('pyproject.toml','r',encoding='utf-8').read()
          m = re.search(r"^version\s*=\s*['\"]([^'\"]+)['\"]", txt, re.M)
          if not m:
            raise SystemExit(1)
          print(m.group(1))
          PY
          )
          TAG="v$VERSION"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists; skipping"
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG"

